# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owaspcalc', '0002_auto_20170330_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskaudit',
            name='awareness',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='owaspcalc.RiskItemDetail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riskaudit',
            name='ease_of_discovery',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='owaspcalc.RiskItemDetail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riskaudit',
            name='ease_of_exploit',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='owaspcalc.RiskItemDetail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riskaudit',
            name='financial_damage',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='owaspcalc.RiskItemDetail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riskaudit',
            name='intrusion_detection',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='owaspcalc.RiskItemDetail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riskaudit',
            name='loss_of_accountability',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='owaspcalc.RiskItemDetail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riskaudit',
            name='loss_of_availability',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='owaspcalc.RiskItemDetail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riskaudit',
            name='loss_of_confidentiality',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='owaspcalc.RiskItemDetail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riskaudit',
            name='loss_of_integrity',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='owaspcalc.RiskItemDetail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riskaudit',
            name='non_compliance',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='owaspcalc.RiskItemDetail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riskaudit',
            name='privacy_violation',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='owaspcalc.RiskItemDetail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riskaudit',
            name='reputation_damage',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='owaspcalc.RiskItemDetail'),
            preserve_default=False,
        ),
    ]
